### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by iminfor** [pruby/otp-brute-test#1]
Hey, I'm a beginner can you please guide me how to use this tool? A quick video on how to add get post and how to capture instagram get post n all.

**Comment by tim-goddard-cybercx** [comment]
Hello,

I have no intention of publishing a video at this time. There are written instructions on the options this supports on the README. More detailed ways of using this are left to your imagination.

**Comment by pruby** [comment]
Hello,

I have no intention of publishing a video at this time. There are written instructions on the options this supports on the README. More detailed ways of using this are left to your imagination.
